### ISSUE TITLE
HTTP 403 FORBIDDEN

### ISSUE THREAD

**Issue by xia3839** [techGay/v9porn#162]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by recolic** [comment]
duplicate of #161

**Comment by godardlouis** [comment]
貌似又不能用了

**Comment by ferdiina** [comment]
应该是91的cdn加速服务 cloudflare 检测到代理问题 跳转到验证网页的问题

**Comment by techGay** [comment]
是这样没错，可能还开了WAF，想到了借用webview解决，有一些思路，不过目前没怎么有时间写

**Comment by ferdiina** [comment]
嗯 简单处理就是检测到403状态码或者cloudflare页面直接跳转 ， 人工手工认证完后 在跳回主页面

**Comment by nh560** [comment]
> 嗯 简单处理就是检测到403状态码或者cloudflare页面直接跳转 ， 人工手工认证完后 在跳回主页面

老铁能加个联系方式吗，请教一些问题

**Comment by ferdiina** [comment]
qq 还是啥
不过其实俺不会编程的说




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nh560"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 下午3:05
收件人:&nbsp;"techGay/v9porn"<v9porn@noreply.github.com&gt;;
抄送:&nbsp;"Fred"<flygg@163.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [techGay/v9porn] HTTP 403 FORBIDDEN (#162)



 
嗯 简单处理就是检测到403状态码或者cloudflare页面直接跳转 ， 人工手工认证完后 在跳回主页面
  
老铁能加个联系方式吗，请教一些问题

**Comment by nh560** [comment]
QQ 1097885640 1097885640 邮箱：1097885640@qq.com 签名由 网易邮箱大师 定制 On 03/03/2020 10:52, Fred wrote: qq 还是啥 不过其实俺不会编程的说 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nh560"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月22日(星期六) 下午3:05 收件人:&nbsp;"techGay/v9porn"<v9porn@noreply.github.com&gt;; 抄送:&nbsp;"Fred"<flygg@163.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [techGay/v9porn] HTTP 403 FORBIDDEN (#162) 嗯 简单处理就是检测到403状态码或者cloudflare页面直接跳转 ， 人工手工认证完后 在跳回主页面 老铁能加个联系方式吗，请教一些问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
